### ISSUE TITLE
keepalived crashed with on/off synproxy

### ISSUE THREAD

**Issue by icymoon** [iqiyi/dpvs#126]
Core was generated by `./keepalived -d -C -f /etc/keepalived/keepalived.conf -S 6'.
Program terminated with signal 6, Aborted.
#0  0x00007f602ddea1f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libgcc-4.8.5-16.el7.x86_64 libselinux-2.5-11.el7.x86_64 nss-softokn-freebl-3.28.3-8.el7_4.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007f602ddea1f7 in raise () from /lib64/libc.so.6
#1  0x00007f602ddeb8e8 in abort () from /lib64/libc.so.6
#2  0x00007f602de29f47 in __libc_message () from /lib64/libc.so.6
#3  0x00007f602de31619 in _int_free () from /lib64/libc.so.6
#4  0x0000000000406da0 in ipvs_stop () at ipvswrapper.c:396
#5  0x000000000040545d in stop_check () at check_daemon.c:60
#6  0x0000000000405585 in start_check () at check_daemon.c:94
#7  0x0000000000405689 in reload_check_thread (thread=<optimized out>) at check_daemon.c:212
#8  0x000000000041facd in thread_call (thread=0x7ffc59d53de0) at scheduler.c:761
#9  launch_scheduler () at scheduler.c:784
#10 0x000000000040575b in start_check_child () at check_daemon.c:311
#11 0x00000000004030a1 in start_keepalived () at main.c:80
#12 main (argc=<optimized out>, argv=<optimized out>) at main.c:303

**Comment by mscbg** [comment]
Reload many times or crash every time?

**Comment by icymoon** [comment]
reload many times T_T
