### ISSUE TITLE
keepalived crashed in reloading, thank you.

### ISSUE THREAD

**Issue by icymoon** [iqiyi/dpvs#159]
Core was generated by `/home/dpvs/dpvs_dpdk/sre_scripts/../dpvs/bin/keepalived -d -C -f /etc/keepalive'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f9530fcf4dc in free () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-8.el7.x86_64 libcom_err-1.42.9-10.el7.x86_64 libselinux-2.5-11.el7.x86_64 nss-softokn-freebl-3.28.3-8.el7_4.x86_64 openssl-libs-1.0.2k-8.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
\#0  0x00007f9530fcf4dc in free () from /lib64/libc.so.6\
\#1  0x0000000000421995 in free_element (l=0x12603b40) at list.c:114
\#2  free_list (l=0x12603b40) at list.c:140
\#3  0x000000000041a0db in free_interface_queue () at vrrp_if.c:409
\#4  0x0000000000405637 in reload_check_thread (thread=<optimized out>) at check_daemon.c:199
\#5  0x000000000042013d in thread_call (thread=0x7ffc2ec3ebd0) at scheduler.c:761
\#6  launch_scheduler () at scheduler.c:784
\#7  0x000000000040575b in start_check_child () at check_daemon.c:311
\#8  0x0000000000405856 in check_respawn_thread (thread=<optimized out>) at check_daemon.c:240
\#9  0x000000000042013d in thread_call (thread=0x7ffc2ec3ec50) at scheduler.c:761
\#10 launch_scheduler () at scheduler.c:784
\#11 0x00000000004030b9 in main (argc=<optimized out>, argv=<optimized out>) at main.c:307

**Comment by mscbg** [comment]
we will update keepalived to try to fix these crash bugs. Thanks for your issues.

**Comment by wangdwcsd** [comment]
@beacer @mscbg Whether the vulnerability has been repaired.thank you
