### ISSUE TITLE
dpvs crashed at dp_vs_laddr_unbind when stress test

### ISSUE THREAD

**Issue by ywc689** [iqiyi/dpvs#187]
crashed stack:
> (gdb) bt                                                                                                                                                                                      
#0  0x000000000055d34e in inet_addr_equal (af=2, a1=0x128, a2=0x7ffff5ecc684) at /home/wencyu/github/dpvs/src/inet.c:72                                                                       
#1  0x000000000055b9db in __ifa_lookup (idev=0x7fff5727cac0, addr=0x7ffff5ecc684, plen=0 '\000') at /home/wencyu/github/dpvs/src/inetaddr.c:99                                                
#2  0x000000000055ca42 in inet_addr_ifa_get (af=2, dev=0x7fff5727cb40, addr=0x7ffff5ecc684) at /home/wencyu/github/dpvs/src/inetaddr.c:534                                                   d
#3  0x00000000005f59b1 in sa_release (dev=0x7fff5727cb40, daddr=0x7ffff5ecc690, saddr=0x7ffff5ecc680) at /home/wencyu/github/dpvs/src/sa_pool.c:580                                           
#4  0x000000000059932d in dp_vs_laddr_unbind (conn=0x7fff02fe0240) at /home/wencyu/github/dpvs/src/ipvs/ip_vs_laddr.c:259                                                                    d
#5  0x000000000058ba44 in conn_expire (priv=0x7fff02fe0240) at /home/wencyu/github/dpvs/src/ipvs/ip_vs_conn.c:433                                                                             
#6  0x0000000000615b18 in timer_expire (sched=0x7ffff5ece668, timer=0x7fff02fe0348) at /home/wencyu/github/dpvs/src/timer.c:193                                                              d
#7  0x0000000000615ccd in rte_timer_tick_cb (tim=0x7ffff5ece688, arg=0x7ffff5ece668) at /home/wencyu/github/dpvs/src/timer.c:267                                                              
#8  0x000000000053a002 in rte_timer_manage ()                                                                                                                                                d
#9  0x00000000005ea753 in lcore_job_timer_manage (args=0x0) at /home/wencyu/github/dpvs/src/netif.c:2345                                                                                      
#10 0x00000000005ee092 in do_lcore_job (job=0x9a4700 <netif_jobs+256>) at /home/wencyu/github/dpvs/src/netif.c:3710                                                                          d
#11 0x00000000005ee1c5 in netif_loop (dummy=0x0) at /home/wencyu/github/dpvs/src/netif.c:3747                                                                                                 
#12 0x00000000005205c4 in eal_thread_loop ()                                                                                                                                                 >
#13 0x00007ffff70d0dc5 in start_thread () from /lib64/libpthread.so.0                                                                                                                         
#14 0x00007ffff6bf221d in clone () from /lib64/libc.so.6                                                                                                                                     >
(gdb) p/x a1                                                                                                                                                                                  
$7 = 0x128                                                                                                                                                                                    
(gdb) p/x a2                                                                                                                                                                                  
$8 = 0x7ffff5ecc684                                                                                                                                                                           
(gdb) 

reproduce script:
> #!/bin/sh
#wrk clients
C=200
D=60
T=20
#dpvs server
server=x.x.x.x
ovip=x.x.x.x
ivip=192.168.88.1
vport=80
BK=$((D/3))
loop=1
while true
do
  echo -e "$(date): test loop $loop"
  ./batch ssh "nohup taskset 0xFFFF0000 wrk -c $C -d $D -t $T http://$ivip:$vport/ > /dev/null 2>&1 &"
  ./batch ssh "nohup taskset 0xFFFF0000 wrk -c $C -d $D -t $T http://$ovip:$vport/ > /dev/null 2>&1 &"
  ./batch ssh "nohup taskset 0xffff00000000 /home/wencyu/udp-test/uperf -c ffff00000000 -s 1 -m 1000 -t $BK $ivip:6000 > /dev/null 2>&1 &"
  sleep $BK
  echo -e "${BK}s passed, restart keepalived"
  ssh root@$server "systemctl restart  keepalived.service"
  ./batch ssh "nohup taskset 0xffff00000000 /home/wencyu/udp-test/uperf -c ffff00000000 -s 1 -m 1000 -t $BK $ivip:6000 > /dev/null 2>&1 &"
  sleep $BK
  echo -e "another ${BK}s passed, restart keepalived"
  ssh root@$server "systemctl restart  keepalived.service"
  ./batch ssh "nohup taskset 0xffff00000000 /home/wencyu/udp-test/uperf -c ffff00000000 -s 1 -m 1000 -t $BK $ivip:6000 > /dev/null 2>&1 &"
  sleep $BK
  sleep 5
  loop=$((loop+1))
done

**Comment by ywc689** [comment]
fix by commit 6ab9a10c11f5b25769e8fd18eedbe3e8c15abed6
