### ISSUE TITLE
执行 ./usertools/dpdk-devbind.py --status报错

### ISSUE THREAD

**Issue by YangEdward** [iqiyi/dpvs#287]
Traceback (most recent call last):
  File "./usertools/dpdk-devbind.py", line 718, in <module>
    main()
  File "./usertools/dpdk-devbind.py", line 711, in main
    get_device_details(network_devices)
  File "./usertools/dpdk-devbind.py", line 273, in get_device_details
    dev_lines = check_output(["lspci", "-Dvmmnnk"]).splitlines()
  File "./usertools/dpdk-devbind.py", line 149, in check_output
    stderr=stderr).communicate()[0]
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by YangEdward** [comment]
VMware虚拟机 centos7.4。网卡信息：
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:3b:e2:9f brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.58/24 brd 192.168.1.255 scope global noprefixroute dynamic ens33
       valid_lft 86326sec preferred_lft 86326sec
    inet 192.168.1.209/24 brd 192.168.1.255 scope global secondary noprefixroute ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::67d:24c:5acc:723c/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: ens34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:3b:e2:a9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.59/24 brd 192.168.1.255 scope global noprefixroute dynamic ens34
       valid_lft 86327sec preferred_lft 86327sec
    inet 192.168.1.210/24 brd 192.168.1.255 scope global secondary noprefixroute ens34
       valid_lft forever preferred_lft forever
    inet6 fe80::cb87:110f:5fd8:e148/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
